lista/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import url, include
from movil.views import home, Fecha_actual, horas_adelante, buscar, empleado,ListaEmpleado, categoria, cargo, prueba
from contactos.views import Index, contactos
from django.conf.urls.static import static

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    #url(r'^$', views.Index),
    url(r'^index/$', Index, name='index'),
    url(r'^buscar/$', buscar),
    url(r'^emp/$', ListaEmpleado,name='ver_lista'),
    url(r'^contactos/$', contactos),
    url(r'^registrar/$', empleado, name='registrar'),
    url(r'^fecha/$', Fecha_actual),
    url(r'^fecha/mas/(\d{1,2})/$', horas_adelante),
    url(r'^categoria/$', categoria, name='categoria'),
    url(r'^home/$', home, name='home'),
    url(r'^cargos/$',cargo, name='cargo'),
    url(r'^prueba/$',prueba, name='prueba')
]

contactos/models.py
from django.db import models

# Create your models here.

contactos/forms.py
from django import forms
class FormularioContactos(forms.Form):
    asunto=forms.CharField(max_length=70)
    email=forms.EmailField(required=False, label='Tu correo electronico')
    mensaje=forms.CharField(widget=forms.Textarea)

    def clean_mensaje(self):
        mensaje=self.cleaned_data['mensaje']
        num_palabras=len(mensaje.split())
        if num_palabras<4:
            raise forms.ValidationError("¡Se requiere minimo 4 palabras!")
        return mensaje

contactos/views.py
from django.shortcuts import render
from django.core.mail import send_mail
from django.http import HttpResponseRedirect, HttpResponse
from contactos.forms import FormularioContactos

# Create your views here.
def Index(request):
    hola="Bienvenidos a mi pagina"
    return render(request, 'inicio.html')

def contactos(request):

    if request.method=='POST':
        form=FormularioContactos(request.POST)
        if form.is_valid():
            cd=form.cleaned_data
            send_mail(request.POST['asunto'], request.POST['mensaje'],
                      request.POST.get('email','nmpc.629@gmail.com'),
                      ['amor_mio65@hotmail.com'])
            return HttpResponseRedirect('/contactos/')
    else:
        form=FormularioContactos()
    return render(request, 'forulario-contactos.html', {'form':form})

contactos/templates/forulario-contactos.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Contactos</title>
</head>
<body>
    <h1>Contactos</h1>
{% if form.errors %}
    <p style="color: red;">Por favor ingrese lo siguiente:</p>


{% endif %}
<form action="" method="post">{% csrf_token %}
    <div class="field">
        {{ form.asunto.errors }}
            <label for="id_asunto">Asunto:</label>
        {{ form.asunto }}
    </div>
    <div class="field">
        {{ form.email.errors }}
            <label for="id_email">E-mail:</label>
        {{ form.email }}
    </div>
    <div class="field">
        {{ form.mensaje.errors }}
            <label for="id_mensaje">Mensaje:</label>
        {{ form.mensaje }}
    </div>
    <input type="submit" value="Enviar">

</form>

</body>
</html>

contactos/templates/inicio.html
{% load static %}
<!DOCTYPE html>
<html>
    <head>
        <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
        <title>Empresa</title>
        <link rel="stylesheet" href="{% static 'resources/css/normalize.css' %}">
        <link rel="stylesheet" href="{% static 'resources/css/sweetalert2.css' %}">
        <link rel="stylesheet" href="{% static 'resources/css/material.min.css' %}">
        <link rel="stylesheet" href="{% static 'resources/css/material-design-iconic-font.min.css' %}">
 
        <!--<link rel="stylesheet" href="<c:url value="/resources/css/jquery.mCustomScrollbar.css"/>"-->
        <link rel="stylesheet" href="{% static 'resources/css/main.css' %}">
    </head>
<body>
	<div class="login-wrap cover">
		<div class="container-login">
			<p class="text-center" style="font-size: 80px;">
				<i class="zmdi zmdi-account-circle"></i>
			</p>
			<p class="text-center text-condensedLight">Ingresa con tu cuenta</p>
            <form method="post" action="iniciar">
				<div class="mdl-textfield mdl-js-textfield mdl-textfield--floating-label">
				    <input Class="mdl-textfield__input" name="usuario"></input>
                                    <label Class="mdl-textfield__label" name="usuario">Usuario</label>
				</div>
				<div class="mdl-textfield mdl-js-textfield mdl-textfield--floating-label">
				    <input Class="mdl-textfield__input" type="password" name="pass"></input>
				    <label Class="mdl-textfield__label" name="pass">Contraseña</label>
				</div>
				<button class="mdl-button mdl-js-button mdl-js-ripple-effect" style="color: #3F51B5; margin: 0 auto; display: block;">
					Ingresar
				</button>
			</form>
		</div>
	</div>
        
        <!--<script src="<c:url value="/resources/js/jquery-1.11.2.min.js"/>"></script>-->
        <script src="{% static 'resources/js/material.min.js' %}"></script>
        <script src="{% static 'resources/js/sweetalert2.min.js' %}"></script>
        <script src="{% static 'resources/js/jquery.mCustomScrollbar.concat.min.js' %}"></script>
        <script src="{% static 'resources/js/main.js' %}"></script>
</body>
</html>